# Generated by Django 3.1.4 on 2021-01-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('author', models.CharField(default='', max_length=50, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('url', models.CharField(default='', max_length=100, null=True)),
                ('url_to_image', models.CharField(default='', max_length=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('office', models.CharField(default='', max_length=50)),
                ('party', models.CharField(default='', max_length=50, null=True)),
                ('image_url', models.CharField(default='', max_length=200, null=True)),
                ('phone', models.CharField(default='', max_length=13, null=True)),
                ('address_line_1', models.CharField(default='', max_length=50, null=True)),
                ('city', models.CharField(default='', max_length=30, null=True)),
                ('state', models.CharField(default='', max_length=2, null=True)),
                ('zip_code', models.CharField(default='', max_length=10, null=True)),
                ('facebook', models.CharField(default='', max_length=50, null=True)),
                ('twitter', models.CharField(default='', max_length=50, null=True)),
                ('youtube', models.CharField(default='', max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
