# Generated by Django 3.1.5 on 2021-01-24 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('author', models.CharField(default='', max_length=50, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('url', models.CharField(default='', max_length=100, null=True)),
                ('url_to_image', models.CharField(default='', max_length=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('title', models.CharField(default='', max_length=200)),
                ('thumbnail', models.CharField(default='', max_length=200)),
                ('reddit_url', models.CharField(default='', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('office', models.CharField(default='', max_length=50)),
                ('party', models.CharField(default='', max_length=50, null=True)),
                ('image_url', models.CharField(default='', max_length=200, null=True)),
                ('phone', models.CharField(default='', max_length=13, null=True)),
                ('address_line_1', models.CharField(default='', max_length=50, null=True)),
                ('city', models.CharField(default='', max_length=30, null=True)),
                ('state', models.CharField(default='', max_length=2, null=True)),
                ('zip_code', models.CharField(default='', max_length=10, null=True)),
                ('facebook', models.CharField(default='', max_length=50, null=True)),
                ('twitter', models.CharField(default='', max_length=50, null=True)),
                ('youtube', models.CharField(default='', max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('constituent', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
