# Generated by Django 3.1.4 on 2021-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('office', models.CharField(default='', max_length=50)),
                ('party', models.CharField(default='', max_length=50, null=True)),
                ('image_url', models.CharField(default='', max_length=200, null=True)),
                ('phone', models.CharField(default='', max_length=13, null=True)),
                ('address_line_1', models.CharField(default='', max_length=50, null=True)),
                ('city', models.CharField(default='', max_length=30, null=True)),
                ('state', models.CharField(default='', max_length=2, null=True)),
                ('zip_code', models.CharField(default='', max_length=10, null=True)),
                ('facebook', models.CharField(default='', max_length=50, null=True)),
                ('twitter', models.CharField(default='', max_length=50, null=True)),
                ('youtube_url', models.CharField(default='', max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
