# Generated by Django 3.1.4 on 2021-01-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='facebook',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='image_url',
            field=models.CharField(default='', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='twitter',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='youtube',
            field=models.CharField(default='', max_length=50, null=True, unique=True),
        ),
    ]
