# Generated by Django 3.1.4 on 2021-01-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politician',
            old_name='youtube_url',
            new_name='youtube',
        ),
    ]
