# Generated by Django 3.1.4 on 2021-01-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0002_auto_20210111_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='youtube',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
