# Generated by Django 3.1.5 on 2021-01-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0002_auto_20210127_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='constituent',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
