# Generated by Django 3.1.4 on 2021-01-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0002_auto_20210109_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, null=True)),
                ('author', models.CharField(default='', max_length=50, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('url', models.CharField(default='', max_length=100, null=True)),
                ('url_to_image', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
