# Generated by Django 3.1.4 on 2021-01-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0003_auto_20210112_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='facebook',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='twitter',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
