# Generated by Django 3.1.4 on 2021-01-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
