# Generated by Django 3.1.4 on 2021-01-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0005_auto_20210112_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('title', models.CharField(default='', max_length=200)),
                ('thumbnail', models.CharField(default='', max_length=200)),
                ('reddit_url', models.CharField(default='', max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
