# Generated by Django 3.1.5 on 2021-01-28 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('politics', '0005_auto_20210127_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='constituent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
