# Generated by Django 3.1.5 on 2021-02-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politics', '0007_auto_20210127_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
