# Generated by Django 3.1.4 on 2020-12-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201214_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='address2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='standarduser',
            name='pol_preference',
            field=models.CharField(choices=[('democratic_party', 'Democratic Party'), ('republican_party', 'Republican Party')], default='', max_length=30),
        ),
    ]
