# Generated by Django 3.1.5 on 2021-02-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_standarduser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='pol_preference',
            field=models.CharField(choices=[('democratic_party', 'Democratic Party'), ('green_party', 'Green Party'), ('independent_party', 'Independent Party'), ('libertarian_party', 'Libertarian Party'), ('republican_party', 'Republican Party'), ('vermont_progressive', 'Vermont Progressive Party'), ('alliance_party', 'Alliance Party'), ('popular_democratic_party', 'Popular Democratic Party'), ('new_progressive', 'New Progressive Party'), ('citizens_victory_movement', "Citizen's Victory Movement"), ('puerto_rican_independence', 'Puerto Rican Independence Party')], default='', max_length=30),
        ),
    ]
